// Print all subsequences of a string
// Given a string, we have to find out all subsequences of it.

// Note: A String is a subsequence of a given String, that is generated by deleting some character of a given string without changing its order.

// Sample Input
// abc
// Sample Output
// a, b, c, ab, bc, ac, abc
// Sample Explanation
// Generate all subsequence of string "abc"
// Expected Time Complexity
// O(2^N*l), where N is length of string to find subsequences and l is length of binary string.

// Expected Space Complexity
// O(N), Auxiliary space

// Constraints
// 1 <= N <= 10

function solution(s) {
  const result = [];

  function subsequences(current, index) {
    if (index === s.length) {
      result.push(current);
      return;
    }

    subsequences(current + s[index], index + 1);

    subsequences(current, index + 1);
  }

  subsequences("", 0);
  return result.sort();
}

console.log(solution("abc"));
